### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getForm() on null in /xxx/public/include/class.plugin.php:1094

### ISSUE THREAD

**Issue by angelandasi** [t-oster/osticket-auto-unassign#1]
Hi,
I just upgraded to the version 1.17 of osTicket. Since then, the plugin is not working properly.
When I go to Admin Panel -> Manage -> Plugins -> Upstart IT Auto Unassign -> Instances Tab -> and click on the instance available,   I am getting an Fatal error: Uncaught Error: .

Does anyone know what I can do to make it work again?
Thank you in advance.

Our osTicket settings:

osTicket Version | v1.17 (1d8b790) —  Up to date
Web Server Software | Apache/2.4.37 () OpenSSL/1.1.1g Phusion_Passenger/6.0.6
MySQL Version | 5.7.34
PHP Version | 8.0.11

This is the entire log message I am getting: (I replaced part of the path with xxx)

Fatal error: Uncaught Error: Call to a member function getForm() on null in /xxx/public/include/class.plugin.php:1094
Stack trace:
#0 /xxx/public/include/staff/templates/plugin-instance.tmpl.php(4): PluginInstance->getForm()
#1 /xxx/public/include/staff/plugin-instance.inc.php(32): include('...')
#2 /xxx/public/scp/plugins.php(136): require('...')
#3 {main} thrown in /xxx/public/include/class.plugin.php on line 1094

**Comment by angelandasi** [comment]
I finally found a solution by myself.

To make is work with the new v1.17, I add to create a config.php file and edited the UitAutoUnassignEdited.php file.

At the same time I took the opportunity to create two options so it can work in two different ways.
One option is the same as before: when assigning to a Team, the Agent is unassigned, and vice versa.
The new option is to be able to have a Team and an Agent assigned, but automatically unassign the Agent when a new Team is assigned.
The second option work better for our way of working.

I am new at github, so if I can I will try to add the files.
